cache_run_c_code = 'Test does not build: Traceback (most recent call last):\n  File "/media/psf/iCloud/Uni/Masterthesis/ss20-ma-kaywallasshek-ml-mptcp/ns3-mptcp/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Tools/c_config.py", line 459, in run_c_code\n    bld.compile()\n  File "/media/psf/iCloud/Uni/Masterthesis/ss20-ma-kaywallasshek-ml-mptcp/ns3-mptcp/.waf-1.7.13-5a064c2686fe54de4e11018d22148cfc/waflib/Build.py", line 188, in compile\n    raise Errors.BuildError(self.producer.error)\nBuildError: Build failed\n -> task in \'testprog\' failed (exit status 1): \n\t{task 139741034978256: cxx test.cpp -> test.cpp.1.o}\n[\'/usr/bin/g++\', \'-std=c++0x\', \'-fPiC\', \'-fno-strict-aliasing\', \'-fwrapv\', \'-fdebug-prefix-map=/build/python2.7-UKCoZ3/python2.7-2.7.17=.\', \'-fstack-protector-strong\', \'-DPYTHONDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DPYTHONARCHDIR="/usr/local/lib/python2.7/dist-packages"\', \'-DNDEBUG\', \'-D_FORTIFY_SOURCE=2\', \'../test.cpp\', \'-c\', \'-o\', \'test.cpp.1.o\']\n'
